# Generated by Django 5.1.1 on 2024-10-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='corse_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('corse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='DUITSsite.corse')),
            ],
        ),
    ]
